//! Database schema definitions generated by Diesel.
//!
//! This module contains the table definitions for the background job system.

#![allow(missing_docs)]

diesel::table! {
    background_jobs (id) {
        id -> Int8,
        job_type -> Text,
        data -> Jsonb,
        retries -> Int4,
        last_retry -> Timestamp,
        created_at -> Timestamp,
        priority -> Int2,
    }
}
